// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApBJ3XkCBYPSLcc4PugxjWAdeNyqfEWHM',
    appId: '1:49491866019:android:336496646dee83d2dd2a16',
    messagingSenderId: '49491866019',
    projectId: 'to-do-best-72308',
    storageBucket: 'to-do-best-72308.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZH3iZrSsQMygx9-XbjpSRIj_z8h7dWm4',
    appId: '1:49491866019:ios:56864e80567c815cdd2a16',
    messagingSenderId: '49491866019',
    projectId: 'to-do-best-72308',
    storageBucket: 'to-do-best-72308.appspot.com',
    androidClientId: '49491866019-k3v15lk3tlkf1kh8dtqdrthu52rjeol8.apps.googleusercontent.com',
    iosClientId: '49491866019-v6l61b579k33s4lil5kaientu75dfj4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationworkCommunity',
  );
}
